import { 
  Tenant, 
  User, 
  Customer, 
  Supplier, 
  Category, 
  Unit, 
  Warehouse, 
  Product, 
  StockMovement, 
  Quotation, 
  SalesInvoice, 
  PurchaseOrder, 
  BillOfMaterials, 
  ProductionOrder, 
  Account, 
  JournalEntry, 
  CashBankAccount, 
  AuditLog, 
  SyncOutboxItem,
  ADRItem,
  ClarificationAnswer,
  Project,
  MeasurementRecord
} from '../types';

export const initialTenant: Tenant = {
  id: 'tenant-1001-fabrication',
  name: 'Al-Andalus Aluminium & Steel Fabrication',
  name_ar: 'ورشة الأندلس للألمنيوم والحدادة الفنية',
  code: 'ANDALUS-01',
  address: 'Sana\'a Industrial Zone, Yemen / المنطقة الصناعية - صنعاء',
  phone: '+967 770 123 456',
  currency: 'YER',
  currency_symbol: 'ر.ي',
  tax_rate: 0.05, // 5% configurable tax
  tax_number: 'TX-967-882190',
  decimal_places: 2,
  costing_method: 'weighted_average',
  created_at: '2026-08-01T08:00:00Z',
};

export const initialUsers: User[] = [
  {
    id: 'user-01',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Khaled Al-Shormani',
    name_ar: 'خالد الشرماني',
    email: 'khaled@alandalus.com',
    role: 'owner',
    active: true,
  },
  {
    id: 'user-02',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Ahmed Al-Haimi',
    name_ar: 'أحمد الحيمي',
    email: 'ahmed@alandalus.com',
    role: 'accountant',
    active: true,
  },
  {
    id: 'user-03',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Yasser Al-Qadi',
    name_ar: 'ياسر القاضي',
    email: 'yasser@alandalus.com',
    role: 'production',
    active: true,
  },
  {
    id: 'user-04',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Sultan Al-Areeqi',
    name_ar: 'سلطان العريقي',
    email: 'sultan@alandalus.com',
    role: 'storekeeper',
    active: true,
  },
];

export const initialCategories: Category[] = [
  { id: 'cat-01', name: 'Aluminium Profiles', name_ar: 'قطاعات الألمنيوم', code: 'ALU-PROF' },
  { id: 'cat-02', name: 'Glass & Glazing', name_ar: 'الزجاج والمسطحات', code: 'GLASS' },
  { id: 'cat-03', name: 'Accessories & Hardware', name_ar: 'الإكسسوارات والمقابض', code: 'ACC-HDW' },
  { id: 'cat-04', name: 'Steel & Metal Sheets', name_ar: 'الحديد والتيوبات والصاج', code: 'STEEL' },
  { id: 'cat-05', name: 'Finished Windows & Doors', name_ar: 'منتجات تامة (أبواب ونوافذ)', code: 'FINISHED' },
  { id: 'cat-06', name: 'Consumables & Gas', name_ar: 'مواد استهلاكية ولحام', code: 'CONSUMABLE' },
];

export const initialUnits: Unit[] = [
  { id: 'u-m', name: 'Meter', name_ar: 'متر طولي', symbol: 'm', base_factor: 1 },
  { id: 'u-sqm', name: 'Square Meter', name_ar: 'متر مربع', symbol: 'm²', base_factor: 1 },
  { id: 'u-pcs', name: 'Piece', name_ar: 'قطعة / حبة', symbol: 'pcs', base_factor: 1 },
  { id: 'u-bar', name: 'Bar (6m)', name_ar: 'عود (6 متر)', symbol: 'bar', base_factor: 6 },
  { id: 'u-kg', name: 'Kilogram', name_ar: 'كيلوجرام', symbol: 'kg', base_factor: 1 },
  { id: 'u-sheet', name: 'Sheet', name_ar: 'لوح', symbol: 'sheet', base_factor: 1 },
];

export const initialWarehouses: Warehouse[] = [
  {
    id: 'wh-01',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Main Workshop Storage',
    name_ar: 'مستودع الورشة الرئيسي',
    code: 'WH-MAIN',
    location: 'Building A, Ground Floor',
    is_default: true,
  },
  {
    id: 'wh-02',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Raw Materials Yard',
    name_ar: 'ساحة تخزين قطاعات الحديد والصلب',
    code: 'WH-YARD',
    location: 'Open Yard Bay 3',
    is_default: false,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'p-alu-profile-saraya',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'ALU-SAR-100',
    name: 'Aluminium Profile Saraya 10cm (White)',
    name_ar: 'قطاع ألمنيوم سرايا 10سم أبيض (عود 6م)',
    description: 'Thermal break structural profile 6 meters bar',
    type: 'profile',
    category_id: 'cat-01',
    unit_id: 'u-bar',
    unit_price: 18500, // in YER
    unit_cost: 14200,
    min_stock: 20,
    max_stock: 200,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: true,
    barcode: '62910023401',
  },
  {
    id: 'p-glass-double-24',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'GLS-DBL-24MM',
    name: 'Double Glazed Glass 24mm (Reflective Blue)',
    name_ar: 'زجاج دبل عاكس أزرق 24مم (متر مربع)',
    description: '6mm Blue + 12mm Air Gap + 6mm Clear',
    type: 'glass',
    category_id: 'cat-02',
    unit_id: 'u-sqm',
    unit_price: 12000,
    unit_cost: 8500,
    min_stock: 30,
    max_stock: 300,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: true,
  },
  {
    id: 'p-acc-sliding-rollers',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'ACC-ROL-ITL',
    name: 'Heavy-duty Sliding Rollers (Italian)',
    name_ar: 'عجلات سحاب إيطالي هيفي ديوتي (طقم)',
    description: 'Double stainless steel bearing wheels for sliding sash',
    type: 'accessory',
    category_id: 'cat-03',
    unit_id: 'u-pcs',
    unit_price: 3200,
    unit_cost: 2100,
    min_stock: 50,
    max_stock: 500,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: true,
  },
  {
    id: 'p-acc-epdm-rubber',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'ACC-EPDM-MTR',
    name: 'EPDM Weatherseal Rubber Gasket',
    name_ar: 'ربل عازل غبار EPDM ألماني (متر)',
    description: 'Acoustic and weatherproofing gasket',
    type: 'accessory',
    category_id: 'cat-03',
    unit_id: 'u-m',
    unit_price: 450,
    unit_cost: 280,
    min_stock: 100,
    max_stock: 2000,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: true,
  },
  {
    id: 'p-steel-tube-4040',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'STL-TUB-4040',
    name: 'Steel Tube Hollow 40x40x2.0mm',
    name_ar: 'تيوب حديد مفرغ 40×40×2.0 مم (عود 6م)',
    description: 'Structural black steel tube for gates and grills',
    type: 'raw',
    category_id: 'cat-04',
    unit_id: 'u-bar',
    unit_price: 11000,
    unit_cost: 8200,
    min_stock: 25,
    max_stock: 250,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: true,
  },
  {
    id: 'p-fin-window-sliding-120',
    tenant_id: 'tenant-1001-fabrication',
    sku: 'WIN-SLD-120120',
    name: 'Aluminium Sliding Window 120x120cm Double Glass',
    name_ar: 'نافذة ألمنيوم سحاب 120×120 سم دبل جلاس سرايا',
    description: 'Finished 2-track sliding window with security screen',
    type: 'finished',
    category_id: 'cat-05',
    unit_id: 'u-pcs',
    unit_price: 65000,
    unit_cost: 44200,
    min_stock: 2,
    max_stock: 20,
    is_stockable: true,
    is_sellable: true,
    is_purchasable: false,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-01',
    tenant_id: 'tenant-1001-fabrication',
    type: 'contractor',
    name: 'Al-Hekmah General Contracting Co.',
    name_ar: 'شركة الحكمة للمقاولات العامة والتطوير العقاري',
    phone: '+967 777 444 888',
    email: 'projects@alhekmah-ye.com',
    address: 'Hadda St., Sana\'a',
    tax_number: 'TX-CUST-8812',
    credit_limit: 5000000,
    opening_balance: 450000,
    current_balance: 1250000,
    status: 'active',
    created_at: '2026-08-05T09:00:00Z',
  },
  {
    id: 'cust-02',
    tenant_id: 'tenant-1001-fabrication',
    type: 'individual',
    name: 'Eng. Omar Al-Jabri (Villa Project)',
    name_ar: 'م. عمر الجابري - مشروع فيلا السبعين',
    phone: '+967 771 990 011',
    address: 'Al-Sabeen District, Sana\'a',
    credit_limit: 1000000,
    opening_balance: 0,
    current_balance: 180000,
    status: 'active',
    created_at: '2026-08-10T11:00:00Z',
  },
  {
    id: 'cust-03',
    tenant_id: 'tenant-1001-fabrication',
    type: 'company',
    name: 'Al-Noor Medical Center Expansion',
    name_ar: 'مركز النور الطبي - توسعة العيادات الخارجية',
    phone: '+967 773 221 155',
    address: 'Baghdad St., Sana\'a',
    credit_limit: 3000000,
    opening_balance: 0,
    current_balance: 0,
    status: 'active',
    created_at: '2026-08-15T14:30:00Z',
  }
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-01',
    tenant_id: 'tenant-1001-fabrication',
    name: 'Gulf Aluminium Profiles Extrusions',
    name_ar: 'سحب قطاعات ألمنيوم الخليج الدولية',
    phone: '+967 770 889 900',
    email: 'sales@gulf-extrusions.com',
    address: 'Aden Road, Taiz Junction',
    category: 'Aluminium Profiles',
    opening_balance: 1200000,
    current_balance: 850000,
    status: 'active',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'sup-02',
    tenant_id: 'tenant-1001-fabrication',
    name: 'National Glass & Tempering Factory',
    name_ar: 'مصنع الزجاج الوطني للسيكوريت والدبل',
    phone: '+967 772 334 455',
    email: 'orders@nationalglass-ye.com',
    address: 'Industrial City, Al-Rawda',
    category: 'Glass',
    opening_balance: 300000,
    current_balance: 140000,
    status: 'active',
    created_at: '2026-08-02T12:00:00Z',
  }
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'sm-01',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-alu-profile-saraya',
    warehouse_id: 'wh-01',
    type: 'purchase_receipt',
    quantity: 80,
    unit_cost: 14200,
    direction: 'in',
    reference_type: 'purchase_order',
    reference_id: 'PO-2026-001',
    notes: 'Initial stock intake from Gulf Extrusions',
    created_by: 'Sultan Al-Areeqi',
    created_at: '2026-08-10T08:30:00Z',
  },
  {
    id: 'sm-02',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-glass-double-24',
    warehouse_id: 'wh-01',
    type: 'purchase_receipt',
    quantity: 120,
    unit_cost: 8500,
    direction: 'in',
    reference_type: 'purchase_order',
    reference_id: 'PO-2026-001',
    notes: 'Batch intake 24mm blue reflective glass',
    created_by: 'Sultan Al-Areeqi',
    created_at: '2026-08-10T08:45:00Z',
  },
  {
    id: 'sm-03',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-acc-sliding-rollers',
    warehouse_id: 'wh-01',
    type: 'purchase_receipt',
    quantity: 200,
    unit_cost: 2100,
    direction: 'in',
    reference_type: 'purchase_order',
    reference_id: 'PO-2026-002',
    notes: 'Italian double bearing rollers',
    created_by: 'Sultan Al-Areeqi',
    created_at: '2026-08-11T09:00:00Z',
  },
  {
    id: 'sm-04',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-acc-epdm-rubber',
    warehouse_id: 'wh-01',
    type: 'purchase_receipt',
    quantity: 600,
    unit_cost: 280,
    direction: 'in',
    reference_type: 'purchase_order',
    reference_id: 'PO-2026-002',
    notes: 'German rubber gasket roll',
    created_by: 'Sultan Al-Areeqi',
    created_at: '2026-08-11T09:15:00Z',
  },
  {
    id: 'sm-05',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-alu-profile-saraya',
    warehouse_id: 'wh-01',
    type: 'production_consumption',
    quantity: 12,
    unit_cost: 14200,
    direction: 'out',
    reference_type: 'production_order',
    reference_id: 'WO-2026-089',
    notes: 'Issued to cutting stage for 6 sliding windows',
    created_by: 'Yasser Al-Qadi',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'sm-06',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-fin-window-sliding-120',
    warehouse_id: 'wh-01',
    type: 'production_output',
    quantity: 6,
    unit_cost: 44200,
    direction: 'in',
    reference_type: 'production_order',
    reference_id: 'WO-2026-089',
    notes: 'Completed fabrication and passed QC',
    created_by: 'Yasser Al-Qadi',
    created_at: '2026-08-22T16:00:00Z',
  },
  {
    id: 'sm-07',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-fin-window-sliding-120',
    warehouse_id: 'wh-01',
    type: 'sale_delivery',
    quantity: 4,
    unit_cost: 44200,
    direction: 'out',
    reference_type: 'invoice',
    reference_id: 'INV-2026-001',
    notes: 'Delivered to Al-Hekmah Project Site',
    created_by: 'Khaled Al-Shormani',
    created_at: '2026-08-25T11:00:00Z',
  }
];

export const initialBOMs: BillOfMaterials[] = [
  {
    id: 'bom-window-sliding-120',
    tenant_id: 'tenant-1001-fabrication',
    product_id: 'p-fin-window-sliding-120',
    name: 'BOM - Sliding Window 120x120cm Saraya',
    name_ar: 'شجرة المواد - نافذة سحاب 120×120 سم قطاع سرايا',
    revision: 1,
    description: 'Standard 2-panel sliding window with 24mm insulated double glass',
    effective_date: '2026-08-01',
    components: [
      {
        id: 'bom-c1',
        product_id: 'p-alu-profile-saraya',
        quantity_formula: '(2 * width + 2 * height + 2 * height + 10) / 600', // Bars of 6m
        formula_type: 'parametric_dimension',
        fixed_quantity: 1.6, // in bars
        waste_factor: 1.08, // 8% cutting waste
        unit: 'bar',
        unit_cost: 14200,
      },
      {
        id: 'bom-c2',
        product_id: 'p-glass-double-24',
        quantity_formula: '(width * height) / 10000', // in sqm
        formula_type: 'area_based',
        fixed_quantity: 1.44, // 1.2m * 1.2m
        waste_factor: 1.04,
        unit: 'm²',
        unit_cost: 8500,
      },
      {
        id: 'bom-c3',
        product_id: 'p-acc-sliding-rollers',
        quantity_formula: '4',
        formula_type: 'fixed',
        fixed_quantity: 4,
        waste_factor: 1.0,
        unit: 'pcs',
        unit_cost: 2100,
      },
      {
        id: 'bom-c4',
        product_id: 'p-acc-epdm-rubber',
        quantity_formula: '(4 * width + 4 * height) / 100',
        formula_type: 'parametric_dimension',
        fixed_quantity: 9.6,
        waste_factor: 1.05,
        unit: 'm',
        unit_cost: 280,
      },
    ],
    labor_hours_estimate: 4.5,
    labor_rate_hourly: 1500, // YER per hour
    overhead_allocation_rate: 3500, // Factory overhead per window
    created_at: '2026-08-01T10:00:00Z',
  }
];

export const initialProductionOrders: ProductionOrder[] = [
  {
    id: 'wo-01',
    tenant_id: 'tenant-1001-fabrication',
    order_number: 'WO-2026-089',
    order_type: 'make-to-order',
    product_id: 'p-fin-window-sliding-120',
    bom_id: 'bom-window-sliding-120',
    customer_id: 'cust-01',
    quotation_id: 'QT-2026-012',
    quantity: 6,
    dimensions: {
      width: 120,
      height: 120,
      color: 'White RAL 9016',
    },
    due_date: '2026-08-30',
    current_stage: 'quality_control',
    stages_history: [
      { stage: 'draft', entered_at: '2026-08-18T08:00:00Z', completed_at: '2026-08-18T09:00:00Z', responsible_employee: 'Khaled' },
      { stage: 'approved', entered_at: '2026-08-18T09:00:00Z', completed_at: '2026-08-19T08:00:00Z', responsible_employee: 'Khaled' },
      { stage: 'materials_reserved', entered_at: '2026-08-19T08:00:00Z', completed_at: '2026-08-19T10:00:00Z', responsible_employee: 'Sultan' },
      { stage: 'materials_issued', entered_at: '2026-08-19T10:00:00Z', completed_at: '2026-08-20T08:00:00Z', responsible_employee: 'Sultan' },
      { stage: 'cutting', entered_at: '2026-08-20T08:00:00Z', completed_at: '2026-08-20T16:00:00Z', responsible_employee: 'Yasser' },
      { stage: 'assembly', entered_at: '2026-08-21T08:00:00Z', completed_at: '2026-08-21T17:00:00Z', responsible_employee: 'Yasser' },
      { stage: 'glass', entered_at: '2026-08-22T08:00:00Z', completed_at: '2026-08-22T14:00:00Z', responsible_employee: 'Yasser' },
      { stage: 'finishing', entered_at: '2026-08-23T08:00:00Z', completed_at: '2026-08-23T15:00:00Z', responsible_employee: 'Yasser' },
      { stage: 'quality_control', entered_at: '2026-08-24T08:00:00Z', responsible_employee: 'Khaled', notes: 'Inspection of corner joints and water sealing' },
    ],
    estimated_material_cost: 195000,
    actual_material_cost: 198200,
    estimated_labor_cost: 40500,
    actual_labor_cost: 39000,
    estimated_overhead_cost: 21000,
    actual_overhead_cost: 21000,
    created_at: '2026-08-18T08:00:00Z',
  },
  {
    id: 'wo-02',
    tenant_id: 'tenant-1001-fabrication',
    order_number: 'WO-2026-090',
    order_type: 'make-to-order',
    product_id: 'p-fin-window-sliding-120',
    bom_id: 'bom-window-sliding-120',
    customer_id: 'cust-02',
    quantity: 3,
    dimensions: {
      width: 140,
      height: 160,
      color: 'Bronze Anodized',
    },
    due_date: '2026-09-05',
    current_stage: 'cutting',
    stages_history: [
      { stage: 'draft', entered_at: '2026-08-25T09:00:00Z', completed_at: '2026-08-25T10:00:00Z', responsible_employee: 'Khaled' },
      { stage: 'approved', entered_at: '2026-08-25T10:00:00Z', completed_at: '2026-08-26T08:00:00Z', responsible_employee: 'Khaled' },
      { stage: 'materials_reserved', entered_at: '2026-08-26T08:00:00Z', completed_at: '2026-08-26T11:00:00Z', responsible_employee: 'Sultan' },
      { stage: 'materials_issued', entered_at: '2026-08-27T08:00:00Z', completed_at: '2026-08-27T09:30:00Z', responsible_employee: 'Sultan' },
      { stage: 'cutting', entered_at: '2026-08-27T09:30:00Z', responsible_employee: 'Yasser', notes: 'Optimized cut plan applied for 6m bars' },
    ],
    estimated_material_cost: 142000,
    actual_material_cost: 142000,
    estimated_labor_cost: 27000,
    actual_labor_cost: 12000,
    estimated_overhead_cost: 10500,
    actual_overhead_cost: 0,
    created_at: '2026-08-25T09:00:00Z',
  }
];

export const initialChartOfAccounts: Account[] = [
  // 1xxxx Assets
  { id: 'acc-1110', tenant_id: 'tenant-1001-fabrication', code: '1110', name: 'Main Workshop Cash Safe', name_ar: 'صندوق الورشة الرئيسي (نقد)', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 1450000 },
  { id: 'acc-1120', tenant_id: 'tenant-1001-fabrication', code: '1120', name: 'Al-Kuraimi Bank Operating Account', name_ar: 'حساب بنك الكريمي التشغيلي', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 4800000 },
  { id: 'acc-1130', tenant_id: 'tenant-1001-fabrication', code: '1130', name: 'Accounts Receivable (Trade Debtors)', name_ar: 'العملاء والمدينون التجاريون', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 1430000 },
  { id: 'acc-1141', tenant_id: 'tenant-1001-fabrication', code: '1141', name: 'Inventory - Raw Materials & Profiles', name_ar: 'مخزون المواد الخام والقطاعات', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 2280000 },
  { id: 'acc-1142', tenant_id: 'tenant-1001-fabrication', code: '1142', name: 'Work in Progress (WIP) Production', name_ar: 'إنتاج تحت التشغيل (WIP)', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 258200 },
  { id: 'acc-1143', tenant_id: 'tenant-1001-fabrication', code: '1143', name: 'Inventory - Finished Fabricated Goods', name_ar: 'مخزون البضاعة تامة الصنع', type: 'asset', category: 'Current Assets', category_ar: 'الأصول المتداولة', is_postable: true, balance: 88400 },
  { id: 'acc-1210', tenant_id: 'tenant-1001-fabrication', code: '1210', name: 'Workshop Machinery & Cutters', name_ar: 'الآلات ومناشير القص ومعدات اللحام', type: 'asset', category: 'Fixed Assets', category_ar: 'الأصول الثابتة', is_postable: true, balance: 12000000 },

  // 2xxxx Liabilities
  { id: 'acc-2110', tenant_id: 'tenant-1001-fabrication', code: '2110', name: 'Accounts Payable (Suppliers)', name_ar: 'الموردون والدائنون التجاريون', type: 'liability', category: 'Current Liabilities', category_ar: 'الالتزامات المتداولة', is_postable: true, balance: 990000 },
  { id: 'acc-2120', tenant_id: 'tenant-1001-fabrication', code: '2120', name: 'Accrued Workshop Wages Payable', name_ar: 'أجور ورواتب العمال المستحقة', type: 'liability', category: 'Current Liabilities', category_ar: 'الالتزامات المتداولة', is_postable: true, balance: 180000 },
  { id: 'acc-2130', tenant_id: 'tenant-1001-fabrication', code: '2130', name: 'Sales Tax Payable', name_ar: 'أمانات ضريبة المبيعات المستحقة', type: 'liability', category: 'Current Liabilities', category_ar: 'الالتزامات المتداولة', is_postable: true, balance: 13000 },

  // 3xxxx Equity
  { id: 'acc-3110', tenant_id: 'tenant-1001-fabrication', code: '3110', name: 'Owner\'s Capital', name_ar: 'رأس مال صاحب الورشة', type: 'equity', category: 'Owner\'s Equity', category_ar: 'حقوق الملكية', is_postable: true, balance: 20000000 },
  { id: 'acc-3120', tenant_id: 'tenant-1001-fabrication', code: '3120', name: 'Retained Earnings', name_ar: 'الأرباح والخسائر المبقاة', type: 'equity', category: 'Owner\'s Equity', category_ar: 'حقوق الملكية', is_postable: true, balance: 1045600 },

  // 4xxxx Revenue
  { id: 'acc-4110', tenant_id: 'tenant-1001-fabrication', code: '4110', name: 'Aluminium Fabrication Sales Revenue', name_ar: 'إيرادات مبيعات وتصنيع الألمنيوم', type: 'revenue', category: 'Operating Revenue', category_ar: 'الإيرادات التشغيلية', is_postable: true, balance: 260000 },
  { id: 'acc-4120', tenant_id: 'tenant-1001-fabrication', code: '4120', name: 'Installation & Site Services Revenue', name_ar: 'إيرادات التركيبات والخدمات الموقعية', type: 'revenue', category: 'Operating Revenue', category_ar: 'الإيرادات التشغيلية', is_postable: true, balance: 45000 },

  // 5xxxx Expenses
  { id: 'acc-5110', tenant_id: 'tenant-1001-fabrication', code: '5110', name: 'Cost of Goods Sold (COGS)', name_ar: 'تكلفة البضاعة المباعة (COGS)', type: 'expense', category: 'Direct Costs', category_ar: 'التكاليف المباشرة', is_postable: true, balance: 176800 },
  { id: 'acc-5120', tenant_id: 'tenant-1001-fabrication', code: '5120', name: 'Direct Workshop Labor Expense', name_ar: 'أجور العمالة المباشرة في الورشة', type: 'expense', category: 'Direct Costs', category_ar: 'التكاليف المباشرة', is_postable: true, balance: 39000 },
  { id: 'acc-5130', tenant_id: 'tenant-1001-fabrication', code: '5130', name: 'Manufacturing Overhead & Electricity', name_ar: 'مصاريف تصنيع غير مباشرة وكهرباء/ديزل', type: 'expense', category: 'Overhead', category_ar: 'المصاريف غير المباشرة', is_postable: true, balance: 21000 },
  { id: 'acc-5210', tenant_id: 'tenant-1001-fabrication', code: '5210', name: 'Workshop Rent Expense', name_ar: 'مصاريف إيجار مبنى الورشة', type: 'expense', category: 'General & Admin', category_ar: 'المصاريف الإدارية والعمومية', is_postable: true, balance: 80000 },
];

export const initialCashBankAccounts: CashBankAccount[] = [
  {
    id: 'cb-01',
    tenant_id: 'tenant-1001-fabrication',
    account_id: 'acc-1110',
    name: 'Workshop Safe (Cash)',
    name_ar: 'خزينة الورشة النقدية',
    type: 'cash',
    currency: 'YER',
    opening_balance: 500000,
    current_balance: 1450000,
  },
  {
    id: 'cb-02',
    tenant_id: 'tenant-1001-fabrication',
    account_id: 'acc-1120',
    name: 'Al-Kuraimi Islamic Bank',
    name_ar: 'بنك الكريمي الإسلامي - حساب جاري',
    type: 'bank',
    account_number: 'YE967-KUR-8839210',
    currency: 'YER',
    opening_balance: 3000000,
    current_balance: 4800000,
  }
];

export const initialJournalEntries: JournalEntry[] = [
  {
    id: 'je-01',
    tenant_id: 'tenant-1001-fabrication',
    entry_number: 'JV-2026-001',
    date: '2026-08-20',
    reference: 'WO-2026-089',
    source_entity: 'wip_material',
    source_id: 'wo-01',
    status: 'posted',
    created_by: 'Ahmed Al-Haimi',
    created_at: '2026-08-20T10:30:00Z',
    lines: [
      { id: 'jel-1', account_id: 'acc-1142', account_code: '1142', account_name: 'Work in Progress (WIP)', description: 'Issued raw materials to WO-2026-089', debit: 198200, credit: 0 },
      { id: 'jel-2', account_id: 'acc-1141', account_code: '1141', account_name: 'Inventory - Raw Materials', description: 'Raw profiles and accessories issued', debit: 0, credit: 198200 },
    ],
    total_debit: 198200,
    total_credit: 198200,
  },
  {
    id: 'je-02',
    tenant_id: 'tenant-1001-fabrication',
    entry_number: 'JV-2026-002',
    date: '2026-08-22',
    reference: 'WO-2026-089',
    source_entity: 'finished_goods',
    source_id: 'wo-01',
    status: 'posted',
    created_by: 'Ahmed Al-Haimi',
    created_at: '2026-08-22T16:30:00Z',
    lines: [
      { id: 'jel-3', account_id: 'acc-1143', account_code: '1143', account_name: 'Inventory - Finished Goods', description: '6 Finished sliding windows completed', debit: 265200, credit: 0 },
      { id: 'jel-4', account_id: 'acc-1142', account_code: '1142', account_name: 'Work in Progress (WIP)', description: 'Transferred completed order to finished inventory', debit: 0, credit: 265200 },
    ],
    total_debit: 265200,
    total_credit: 265200,
  },
  {
    id: 'je-03',
    tenant_id: 'tenant-1001-fabrication',
    entry_number: 'JV-2026-003',
    date: '2026-08-25',
    reference: 'INV-2026-001',
    source_entity: 'sales_invoice',
    source_id: 'inv-01',
    status: 'posted',
    created_by: 'Ahmed Al-Haimi',
    created_at: '2026-08-25T11:30:00Z',
    lines: [
      { id: 'jel-5', account_id: 'acc-1130', account_code: '1130', account_name: 'Accounts Receivable', description: 'Sale on credit to Al-Hekmah Co.', debit: 273000, credit: 0 },
      { id: 'jel-6', account_id: 'acc-4110', account_code: '4110', account_name: 'Aluminium Sales Revenue', description: 'Sale of 4 sliding windows', debit: 0, credit: 260000 },
      { id: 'jel-7', account_id: 'acc-2130', account_code: '2130', account_name: 'Sales Tax Payable', description: '5% tax on invoice', debit: 0, credit: 13000 },
      { id: 'jel-8', account_id: 'acc-5110', account_code: '5110', account_name: 'Cost of Goods Sold (COGS)', description: 'COGS for 4 units @ 44,200', debit: 176800, credit: 0 },
      { id: 'jel-9', account_id: 'acc-1143', account_code: '1143', account_name: 'Inventory - Finished Goods', description: 'Inventory reduced by 4 units', debit: 0, credit: 176800 },
    ],
    total_debit: 449800,
    total_credit: 449800,
  }
];

export const initialSalesInvoices: SalesInvoice[] = [
  {
    id: 'inv-01',
    tenant_id: 'tenant-1001-fabrication',
    invoice_number: 'INV-2026-001',
    customer_id: 'cust-01',
    quotation_id: 'QT-2026-012',
    date: '2026-08-25',
    due_date: '2026-09-25',
    status: 'posted',
    payment_status: 'partial',
    lines: [
      {
        id: 'invl-01',
        product_id: 'p-fin-window-sliding-120',
        description: 'Aluminium Sliding Window 120x120cm Saraya White (Double Glazed)',
        quantity: 4,
        unit_price: 65000,
        discount: 0,
        tax_rate: 0.05,
        subtotal: 260000,
        total: 273000,
      }
    ],
    subtotal: 260000,
    tax_amount: 13000,
    discount_amount: 0,
    total_amount: 273000,
    paid_amount: 100000,
    warehouse_id: 'wh-01',
    created_at: '2026-08-25T11:00:00Z',
  }
];

export const initialQuotations: Quotation[] = [
  {
    id: 'qt-01',
    tenant_id: 'tenant-1001-fabrication',
    quote_number: 'QT-2026-012',
    customer_id: 'cust-01',
    revision: 1,
    status: 'converted',
    date: '2026-08-15',
    valid_until: '2026-09-15',
    items: [
      {
        id: 'qti-01',
        product_id: 'p-fin-window-sliding-120',
        description: 'Aluminium Sliding Window 120x120cm Double Glass Saraya',
        quantity: 6,
        width: 120,
        height: 120,
        unit_price: 65000,
        discount: 0,
        tax_rate: 0.05,
        total: 409500,
        estimated_cost: 265200,
      }
    ],
    subtotal: 390000,
    discount_amount: 0,
    tax_amount: 19500,
    total_amount: 409500,
    estimated_profit_margin: 32.0,
    notes: 'Includes delivery and silicone sealing on site.',
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'qt-02',
    tenant_id: 'tenant-1001-fabrication',
    quote_number: 'QT-2026-015',
    customer_id: 'cust-02',
    revision: 2,
    status: 'approved',
    date: '2026-08-24',
    valid_until: '2026-09-24',
    items: [
      {
        id: 'qti-02',
        product_id: 'p-fin-window-sliding-120',
        description: 'Aluminium Sliding Window 140x160cm Bronze Double Glass',
        quantity: 3,
        width: 140,
        height: 160,
        unit_price: 88000,
        discount: 4000,
        tax_rate: 0.05,
        total: 273000,
        estimated_cost: 179500,
      }
    ],
    subtotal: 260000,
    discount_amount: 4000,
    tax_amount: 13000,
    total_amount: 273000,
    estimated_profit_margin: 31.6,
    notes: 'Revised quotation with bronze color specification.',
    created_at: '2026-08-24T14:00:00Z',
  }
];

export const initialSyncOutbox: SyncOutboxItem[] = [
  {
    id: 'box-01',
    tenant_id: 'tenant-1001-fabrication',
    local_entity: 'sales_invoices',
    local_id: 'inv-01',
    operation: 'INSERT',
    payload: { invoice_number: 'INV-2026-001', customer_id: 'cust-01', total_amount: 273000 },
    status: 'synced',
    retry_count: 0,
    created_at: '2026-08-25T11:05:00Z',
    last_attempt: '2026-08-25T11:05:02Z',
  },
  {
    id: 'box-02',
    tenant_id: 'tenant-1001-fabrication',
    local_entity: 'stock_movements',
    local_id: 'sm-07',
    operation: 'INSERT',
    payload: { product_id: 'p-fin-window-sliding-120', quantity: 4, type: 'sale_delivery' },
    status: 'synced',
    retry_count: 0,
    created_at: '2026-08-25T11:05:00Z',
    last_attempt: '2026-08-25T11:05:02Z',
  },
  {
    id: 'box-03',
    tenant_id: 'tenant-1001-fabrication',
    local_entity: 'production_orders',
    local_id: 'wo-02',
    operation: 'UPDATE',
    payload: { order_number: 'WO-2026-090', current_stage: 'cutting' },
    status: 'pending',
    retry_count: 0,
    created_at: '2026-08-28T14:30:00Z',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-01',
    tenant_id: 'tenant-1001-fabrication',
    user_name: 'Khaled Al-Shormani',
    device_id: 'Android-Tab-GalaxyS8-01',
    entity: 'ProductionOrder',
    action: 'CREATE',
    record_id: 'WO-2026-089',
    details: 'Created make-to-order production order for 6 sliding windows',
    details_ar: 'إنشاء أمر تشغيل وتصنيع لعدد 6 نوافذ سحاب سرايا',
    created_at: '2026-08-18T08:00:00Z',
  },
  {
    id: 'log-02',
    tenant_id: 'tenant-1001-fabrication',
    user_name: 'Sultan Al-Areeqi',
    device_id: 'Android-Phone-Redmi-02',
    entity: 'StockMovement',
    action: 'POST',
    record_id: 'SM-05',
    details: 'Issued 12 bars Saraya Profile from Main Warehouse to cutting bay',
    details_ar: 'صرف 12 عود قطاع سرايا من المستودع الرئيسي لصالة القص',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'log-03',
    tenant_id: 'tenant-1001-fabrication',
    user_name: 'Ahmed Al-Haimi',
    device_id: 'Android-Tab-GalaxyS8-01',
    entity: 'JournalEntry',
    action: 'POST',
    record_id: 'JV-2026-003',
    details: 'Posted balanced sales invoice journal entry debit AR 273,000 YER',
    details_ar: 'ترحيل قيد فاتورة المبيعات المتزن مدين العملاء 273,000 ر.ي',
    created_at: '2026-08-25T11:30:00Z',
  }
];

export const initialADRs: ADRItem[] = [
  {
    id: 'ADR-001',
    title: 'Offline-First Architecture',
    title_ar: 'معمارية العمل دون اتصال أولاً (Offline-First)',
    decision: 'Local SQLite is the primary data store; cloud sync is secondary.',
    decision_ar: 'قاعدة بيانات SQLite المحلية هي المصدر الحقيقي المعتمد للبيانات والمزامنة السحابية ثانوية.',
    reason: 'Workshop environments often have unreliable internet. Operations must continue with zero friction.',
    reason_ar: 'بيئة الورش الصناعية تعاني من انقطاع متكرر للإنترنت، ويجب ألا تتعطل العمليات الإنتاجية والمبيعات إطلاقاً.',
    implications: 'Requires robust outbox queue, idempotency, and entity-level conflict handling.',
    implications_ar: 'تتطلب محرك تزامن متين بنمط Outbox وإلغاء الازدواجية ومعالجة التعارض حسب الكيان.',
  },
  {
    id: 'ADR-002',
    title: 'Local SQLite with SQLCipher',
    title_ar: 'تشفير قاعدة البيانات المحلية عبر SQLCipher',
    decision: 'Use SQLite on device, encrypted with 256-bit SQLCipher linked to Keystore.',
    decision_ar: 'استخدام SQLite مشفرة بتشفير SQLCipher ومفاتيح محمية داخل Android Keystore.',
    reason: 'Physical protection of customer financials, quotations, and accounting data on workshop devices.',
    reason_ar: 'حماية بيانات العملاء والتكاليف المالية ودفاتر الحسابات من الاستخراج غير المصرح به في حال فقدان الجهاز.',
    implications: 'Key management and secure local backup password encryption required.',
    implications_ar: 'ضرورة إدارة مفاتيح التشفير ودعم النسخ الاحتياطي المشفر بكلمة مرور.',
  },
  {
    id: 'ADR-003',
    title: 'UUID Primary Keys',
    title_ar: 'المفاتيح الأساسية بصيغة UUID عالمية',
    decision: 'Use UUIDv4 strings for all entity IDs created offline.',
    decision_ar: 'استخدام صيغة المعرف الفريد عالمياً (UUID) لكافة السجلات والكيانات المنشأة دون اتصال.',
    reason: 'Allows multiple devices in the workshop to generate invoices, stock moves, and work orders simultaneously without ID collision.',
    reason_ar: 'تتيح للعديد من الأجهزة داخل الورشة إنشاء فواتير وسندات مخزنية وأوامر عمل في وقت واحد دون تضارب بالأرقام التسلسلية.',
    implications: 'Requires indexed lookups and human-readable sequence numbers for printed documents.',
    implications_ar: 'تتطلب فهرسة دقيقة وتوليد تسلسلات رقمية مقروءة للمستندات المطبوعة.',
  },
  {
    id: 'ADR-004',
    title: 'Double-Entry Accounting Engine',
    title_ar: 'محرك محاسبي متكامل بنظام القيد المزدوج',
    decision: 'Implement full double-entry accounting engine integrated with all inventory, sales, and manufacturing events.',
    decision_ar: 'تطبيق نظام القيد المزدوج الإلزامي المتزن وربطه آلياً بكافة أحداث المخازن والإنتاج والمبيعات.',
    reason: 'Removes the need for external accounting software and provides auditable cost-of-goods and profit margins.',
    reason_ar: 'يغني الورشة عن برامج محاسبية منفصلة ويقدم احتساباً دقيقاً لتكلفة الإنتاج وهامش الربح الحقيقي.',
    implications: 'Journal entries are strictly immutable once posted; corrections only via reversal entries.',
    implications_ar: 'القيود المرحلة غير قابلة للتعديل أو الحذف، ويتم التصحيح حصراً بقيود عكسية موثقة.',
  },
  {
    id: 'ADR-005',
    title: 'Immutable Inventory Movement Model',
    title_ar: 'سجل الحركات المخزنية غير القابل للتعديل',
    decision: 'All stock balances are derived from immutable stock movements; direct quantity editing is strictly forbidden.',
    decision_ar: 'أرصدة المخازن تُحسب تراكمياً من الحركات المخزنية غير القابلة للتعديل ويُمنع تعديل الرصيد مباشرة.',
    reason: 'Maintains 100% auditability for scrap, cut wastage, and production material issuance.',
    reason_ar: 'يضمن تتبعاً تاماً للهوالك ونفايات القص ومواد الإنتاج المصروفة دون تلاعب.',
    implications: 'Adjustments require dedicated adjustment transactions with audit trails.',
    implications_ar: 'التسويات الجردية تتم بسندات تسوية مخصصة تُسجل في الأثر التدقيقي.',
  },
  {
    id: 'ADR-006',
    title: 'Manufacturing & Parametric BOM Model',
    title_ar: 'نموذج التصنيع وشجرة المواد المتغيرة بالأبعاد',
    decision: 'Support make-to-order & make-to-stock with dimension-based BOM formulas and stage progression.',
    decision_ar: 'دعم التصنيع حسب الطلب وللمخزن مع معادلات شجرة مواد تحسب الأطوال والمساحات بناءً على أبعاد العميل.',
    reason: 'Fabrication in aluminium and steel is dimension-driven (width, height, area) rather than static piece count.',
    reason_ar: 'تصنيع الألمنيوم والحديد يعتمد كلياً على أبعاد متغيرة (عرض، ارتفاع، مسطح) وليس على كميات ثابتة.',
    implications: 'Formula engine must calculate profile lengths, glass areas, and calculate cutting waste.',
    implications_ar: 'محرك المعادلات يجب أن يقدر استهلاك العيدان والمساحات ونسبة الهالك بدقة.',
  },
  {
    id: 'ADR-007',
    title: 'Outbox Pattern Sync Engine',
    title_ar: 'محرك التزامن بنمط صندوق الصادر (Outbox Pattern)',
    decision: 'Transactions atomically write to business tables and the sync_outbox table in a single local commit.',
    decision_ar: 'تُكتب المعاملة محلياً إلى جداول الأعمال وجدول صندوق الصادر (Outbox) في عملية ذرية واحدة.',
    reason: 'Guarantees that no offline change is lost and enables reliable retry mechanisms with backoff.',
    reason_ar: 'يضمن عدم فقدان أي حركة تمت دون اتصال ويوفر إعادة المحاولة التلقائية عند توفر الشبكة.',
    implications: 'Sync worker runs in the background and reports sync states and retry queues.',
    implications_ar: 'يعمل محرك التزامن في الخلفية ويعرض للمستخدم حالة العمليات المعلقة وقيد الإرسال.',
  },
];

export const initialClarifications: ClarificationAnswer[] = [
  {
    id: 1,
    question: 'Are there any legal requirements for invoice numbering or tax reporting in Yemen that we must adhere to initially?',
    question_ar: 'هل هناك متطلبات قانونية لتسلسل الفواتير أو الإقرارات الضريبية في اليمن يجب الالتزام بها مبدئياً؟',
    proposed_answer: 'Implement configurable tax engine with standard 5% sales tax rate, sequential printable invoice numbers per fiscal year (INV-YYYY-XXXX), tax ID registration fields, and QR code capability ready for Zakat and Tax Authority guidelines.',
    proposed_answer_ar: 'اعتماد محرك ضرائب مرن بمعدل ضريبة مبيعات 5% افتراضياً، وتسلسل فواتير سنوي موثق (INV-YYYY-XXXX)، وحقول الرقم الضريبي، ورمز QR جاهز لمتطلبات مصلحة الضرائب والواجبات الزكوية.',
    status: 'confirmed',
  },
  {
    id: 2,
    question: 'Should the system support multiple currencies from the start, or only one base currency?',
    question_ar: 'هل يجب أن يدعم النظام عملات متعددة من البداية أم عملة أساسية واحدة؟',
    proposed_answer: 'Base currency per tenant (e.g. YER / SAR / USD) with multi-currency quotation exchange conversion rate helpers at the transaction level, while General Ledger posts in the tenant\'s base fiscal currency.',
    proposed_answer_ar: 'الاعتماد على عملة أساسية للمستأجر (مثل الريال اليمني YER أو السعودي SAR أو الدولار USD) مع محول أسعار صرف لعروض الأسعار والفواتير، مع ترحيل قيود دفتر الأستاذ العام بالعملة الأساسية.',
    status: 'confirmed',
  },
  {
    id: 3,
    question: 'What is the expected initial number of tenants if SaaS? Or is it single tenant first?',
    question_ar: 'ما هو عدد المستأجرين المتوقع في البداية إن كان نظام سحابي، أم يبدأ كمستأجر واحد للورشة؟',
    proposed_answer: 'Multi-tenant architecture from day 1 with tenant_id isolation in all tables and RLS, initialized for a primary standalone workshop instance that can seamlessly scale to multi-workshop SaaS.',
    proposed_answer_ar: 'معمارية متعددة المستأجرين (Multi-Tenant) من اليوم الأول مع عزل tenant_id في جميع الجداول وقواعد الأمان، وتجهيزه ليعمل كنسخة ورشة رئيسية مع إمكانية التوسع لسحابة متعددة الورش.',
    status: 'confirmed',
  },
  {
    id: 4,
    question: 'Are there any existing workflows in the workshop (e.g., paper forms) that must be mirrored exactly?',
    question_ar: 'هل توجد نماذج ورقية أو مسوحات موقعية متبعة في الورش يجب محاكاتها بدقة؟',
    proposed_answer: 'Include a dedicated Site Survey & Measurements form (نافذة/باب/واجهة) recording Width x Height, opening type, color RAL, glass spec, and notes, mirroring standard workshop technician clipboards.',
    proposed_answer_ar: 'تضمين نموذج إلكتروني للمسوحات الموقعية والمقاسات يسجل (العرض × الارتفاع، نوع الفتحة سحاب/مفصلي، كود اللون RAL، نوع الزجاج) يطابق استمارة الفنيين الميدانية بدقة.',
    status: 'confirmed',
  },
  {
    id: 5,
    question: 'Do you require bilingual (Arabic/English) UI from the start, or Arabic only initially?',
    question_ar: 'هل يشترط واجهة ثنائية اللغة (عربي/إنجليزي) من البداية أم عربية فقط؟',
    proposed_answer: 'Arabic-first RTL layout with an instant one-click toggle to English LTR, catering to Arabic workshop owners, expatriate technicians, and bilingual accountants.',
    proposed_answer_ar: 'واجهة عربية أصيلة مع دعم كامل للاتجاه من اليمين لليسار RTL، مع إمكانية التبديل الفوري للإنجليزية LTR لتسهيل العمل للعمالة الفنية والمحاسبين.',
    status: 'confirmed',
  }
];

export const initialProjects: Project[] = [
  {
    id: 'proj-01',
    tenant_id: 'tenant-1001-fabrication',
    project_code: 'PRJ-2026-001',
    name: 'Al-Haddad Residential Villa',
    name_ar: 'فيلا الحداد السكنية - حدة',
    customer_id: 'cust-01',
    location: 'Hadda District, Sana\'a / حي حدة - صنعاء',
    status: 'in_progress',
    start_date: '2026-08-10',
    end_date: '2026-09-15',
    total_contract_value: 3500000,
    notes: 'Complete aluminium windows, double-glazed soundproof doors and decorative structural handrails.',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'proj-02',
    tenant_id: 'tenant-1001-fabrication',
    project_code: 'PRJ-2026-002',
    name: 'Saba Commercial Tower Facades',
    name_ar: 'واجهات برج سبأ التجاري',
    customer_id: 'cust-02',
    location: 'Zubairy St, Sana\'a / شارع الزبيري - صنعاء',
    status: 'active',
    start_date: '2026-08-15',
    end_date: '2026-10-30',
    total_contract_value: 12800000,
    notes: 'Structural curtain walls, thermal break profiles and reflective blue tempered glass.',
    created_at: '2026-08-15T09:30:00Z',
  },
  {
    id: 'proj-03',
    tenant_id: 'tenant-1001-fabrication',
    project_code: 'PRJ-2026-003',
    name: 'Al-Nour Educational Complex',
    name_ar: 'مجمع النور التعليمي',
    customer_id: 'cust-03',
    location: 'Airport Road, Sana\'a / خط المطار - صنعاء',
    status: 'planning',
    start_date: '2026-09-01',
    total_contract_value: 5400000,
    notes: 'Classroom sliding windows and heavy-duty steel safety gates.',
    created_at: '2026-08-20T11:00:00Z',
  },
];

export const initialMeasurements: MeasurementRecord[] = [
  {
    id: 'meas-01',
    tenant_id: 'tenant-1001-fabrication',
    project_id: 'proj-01',
    customer_id: 'cust-01',
    tag_number: 'W-01',
    location_name: 'Master Bedroom - South Facing',
    location_name_ar: 'غرفة النوم الرئيسية - الواجهة الجنوبية',
    product_type: 'sliding_window',
    width: 150,
    height: 120,
    depth: 10,
    quantity: 2,
    color: 'White RAL 9016',
    glass_spec: 'Double Glazed 6mm Clear / 12mm Air / 6mm Low-E',
    status: 'converted_to_bom',
    notes: 'Include heavy duty roller hardware and stainless steel mesh.',
    created_at: '2026-08-12T09:00:00Z',
  },
  {
    id: 'meas-02',
    tenant_id: 'tenant-1001-fabrication',
    project_id: 'proj-01',
    customer_id: 'cust-01',
    tag_number: 'D-01',
    location_name: 'Living Room Balcony Access',
    location_name_ar: 'مخرج بلكونة الصالة الكبرى',
    product_type: 'sliding_door',
    width: 200,
    height: 220,
    depth: 12,
    quantity: 1,
    color: 'Bronze Metallic RAL 8019',
    glass_spec: 'Tempered 8mm Tinted Grey Glass',
    status: 'verified',
    notes: 'Reinforced interlocking profile for wind load.',
    created_at: '2026-08-12T09:45:00Z',
  },
  {
    id: 'meas-03',
    tenant_id: 'tenant-1001-fabrication',
    project_id: 'proj-01',
    customer_id: 'cust-01',
    tag_number: 'HR-01',
    location_name: 'Internal Staircase Balustrade',
    location_name_ar: 'درابزين السلم الداخلي',
    product_type: 'handrail',
    width: 600,
    height: 100,
    depth: 8,
    quantity: 1,
    color: 'Anodized Silver / كروم فضي',
    glass_spec: 'Laminated 10mm Safety Glass',
    status: 'draft',
    notes: 'Structural floor-mounted spigots every 100cm.',
    created_at: '2026-08-12T10:30:00Z',
  },
  {
    id: 'meas-04',
    tenant_id: 'tenant-1001-fabrication',
    project_id: 'proj-02',
    customer_id: 'cust-02',
    tag_number: 'W-02',
    location_name: 'Office Room Floor 3',
    location_name_ar: 'مكاتب الدور الثالث',
    product_type: 'hinged_window',
    width: 100,
    height: 140,
    depth: 10,
    quantity: 4,
    color: 'Anthracite Grey RAL 7016',
    glass_spec: 'Reflective Blue 6mm Glass',
    status: 'verified',
    notes: 'Multi-point security lock casement sash.',
    created_at: '2026-08-16T14:00:00Z',
  },
];

